# Polygon data (collected from polygon using {datapasta})
pdat <- tibble::tribble(
  ~Critter.number,           ~Fish,             ~Location,       ~Shadow.Size, ~Value,                           ~Time,                                ~Month.Hemisphere,
  1L,           "Bitterling",            "River",      "Smallest",    900,                  "All.day",                                                   "November-March.(Northern)./.May-September.(Southern)",
  2L,           "Pale Chub",            "River",      "Smallest",    160,                  "9 a.m. - 4 p.m.",                                                   "Year-round (Northern and Southern)",
  3L,        "Crucian Carp",            "River",         "Small",    160,                          "All day",                                                   "Year-round (Northern and Southern)",
  4L,                "Dace",            "River",        "Medium",    240,                  "4 p.m. - 9 a.m.",                                                   "Year-round (Northern and Southern)",
  5L,                "Carp",             "Pond",         "Large",    300,                          "All day",                                                   "Year-round (Northern and Southern)",
  6L,                 "Koi",             "Pond",         "Large",   4000,                  "4 p.m. - 9 a.m.",                                                   "Year-round (Northern and Southern)",
  7L,            "Goldfish",             "Pond",      "Smallest",   1300,                          "All day",                                                   "Year-round (Northern and Southern)",
  8L,   "Pop-eyed Goldfish",             "Pond",      "Smallest",   1300,                  "9 a.m. - 4 p.m.",                                                   "Year-round (Northern and Southern)",
  9L,     "Ranchu Goldfish",             "Pond",         "Small",   4500,                  "9 a.m. - 4 p.m.",                                                   "Year-round (Northern and Southern)",
  10L,           "Killifish",             "Pond",      "Smallest",    300,                          "All day",                                "April-August (Northern) / October-February (Southern)",
  11L,            "Crawfish",             "Pond",         "Small",    200,                          "All day",                                "April-September (Northern) / October-March (Southern)",
  12L, "Soft-shelled Turtle",            "River",         "Large",   3750,                  "4 p.m. - 9 a.m.",                              "August-September (Northern) / February-March (Southern)",
  13L,     "Snapping Turtle",            "River",       "X Large",   5000,                  "9 p.m. - 4 a.m.",                                  "April-October (Northern) / October-April (Southern)",
  14L,             "Tadpole",             "Pond",      "Smallest",    100,                          "All day",                                 "March-July (Northern) / September-January (Southern)",
  15L,                "Frog",             "Pond",         "Small",    120,                          "All day",                                 "May-August (Northern) / November-Feburary (Southern)",
  16L,     "Freshwater Goby",            "River",         "Small",    400,                  "4 p.m. - 9 a.m.",                                                   "Year-round (Northern and Southern)",
  17L,               "Loach",            "River",         "Small",    400,                          "All day",                                 "March-May (Northern) / September-November (Southern)",
  18L,             "Catfish",             "Pond",         "Large",    800,                  "4 p.m. - 9 a.m.",                                   "May-October (Northern) / November-April (Southern)",
  19L,     "Giant Snakehead",             "Pond",       "X Large",   5500,                  "9 a.m. - 4 p.m.",                                "June-August (Northern) / December-February (Southern)",
  20L,            "Bluegill",            "River",         "Small",    180,                  "9 a.m. - 4 p.m.",                                                   "Year-round (Northern and Southern)",
  21L,        "Yellow Perch",            "River",        "Medium",    300,                          "All day",                                "October-March (Northern) / April-September (Southern)",
  22L,          "Black Bass",            "River",         "Large",    400,                          "All day",                                                   "Year-round (Northern and Southern)",
  23L,             "Tilapia",            "River",        "Medium",    800,                          "All day",                                  "June-October (Northern) / December-April (Southern)",
  24L,                "Pike",            "River",       "X Large",   1800,                          "All day",                                "September-December (Northern) / March-June (Southern)",
  25L,          "Pond Smelt",            "River",         "Small",    500,                          "All day",                                "December-February (Northern) / June-August (Southern)",
  26L,           "Sweetfish",            "River",        "Medium",    900,                          "All day",                                 "July-September (Northern) / January-March (Southern)",
  27L,       "Cherry Salmon", "River (Clifftop)",        "Medium",   1000,                  "4 p.m. - 9 a.m.", "March-June, September-November (Northern) / March-May, September-December (Southern)",
  28L,                "Char", "River (Clifftop)",        "Medium",   3800,                  "4 p.m. - 9 a.m.", "March-June, September-November (Northern) / March-May, September-December (Southern)",
  29L,        "Golden Trout", "River (Clifftop)",        "Medium",  15000,                  "4 p.m. - 9 a.m.", "March-June, September-November (Northern) / March-May, September-December (Southern)",
  30L,          "Stringfish", "River (Clifftop)",       "Largest",  15000,                  "4 p.m. - 9 a.m.",                                "December-March (Northern) / June-September (Southern)",
  31L,              "Salmon",    "River (mouth)",         "Large",    700,                          "All day",                                              "September (Northern) / March (Southern)",
  32L,         "King Salmon",    "River (mouth)",       "Largest",   1800,                          "All day",                                              "September (Northern) / March (Southern)",
  33L,         "Mitten Crab",            "River",         "Small",   2000,                  "4 p.m. - 9 a.m.",                                 "September-November (Northern) / March-May (Southern)",
  34L,               "Guppy",            "River",      "Smallest",   1300,                  "9 a.m. - 4 p.m.",                                   "April-November (Northern) / October-May (Southern)",
  35L,         "Nibble Fish",            "River",         "Small",   1500,                  "9 a.m. - 4 p.m.",                                 "May-September (Northern) / November-March (Southern)",
  36L,           "Angelfish",            "River",         "Small",   3000,                  "4 p.m. - 9 a.m.",                                   "May-October (Northern) / November-April (Southern)",
  37L,               "Betta",            "River",         "Small",   2500,                  "9 a.m. - 4 p.m.",                                   "May-October (Northern) / November-April (Southern)",
  38L,          "Neon Tetra",            "River",      "Smallest",    500,                  "9 a.m. - 4 p.m.",                                   "April-November (Northern) / October-May (Southern)",
  39L,         "Rainbowfish",            "River",         "Small",    800,                  "9 a.m. - 4 p.m.",                                   "May-October (Northern) / November-April (Southern)",
  40L,             "Piranha",            "River",         "Small",   2500, "9 a.m. - 4 p.m., 9 p.m. - 4 a.m.",                                "June-September (Northern) / December-March (Southern)",
  41L,             "Arowana",            "River",         "Large",  10000,                  "4 p.m. - 9 a.m.",                                "June-September (Northern) / December-March (Southern)",
  42L,              "Dorado",            "River",       "X Large",  15000,                  "4 a.m. - 9 p.m.",                                "June-September (Northern) / December-March (Southern)",
  43L,                 "Gar",             "Pond",       "Largest",   6000,                  "4 p.m. - 9 a.m.",                                "June-September (Northern) / December-March (Southern)",
  44L,            "Arapaima",            "River",       "Largest",  10000,                  "4 p.m. - 9 a.m.",                                "June-September (Northern) / December-March (Southern)",
  45L,      "Saddled Bichir",            "River",         "Large",   4000,                  "9 p.m. - 4 a.m.",                                "June-September (Northern) / December-March (Southern)",
  46L,            "Sturgeon",    "River (mouth)",       "Largest",  10000,                          "All day",                              "September-March (Northern) / March-September (Southern)",
  47L,       "Sea Butterfly",              "Sea",      "Smallest",   1000,                          "All day",                                "December-March (Northern) / June-September (Southern)",
  48L,           "Sea Horse",              "Sea",      "Smallest",   1100,                          "All day",                                   "April-November (Northern) / October-May (Southern)",
  49L,          "Clown Fish",              "Sea",      "Smallest",    650,                          "All day",                                "April-September (Northern) / October-March (Southern)",
  50L,         "Surgeonfish",              "Sea",         "Small",   1000,                          "All day",                                "April-September (Northern) / October-March (Southern)",
  51L,      "Butterfly Fish",              "Sea",         "Small",   1000,                          "All day",                                "April-September (Northern) / October-March (Southern)",
  52L,        "Napoleonfish",              "Sea",       "Largest",  10000,                  "4 a.m. - 9 p.m.",                                 "July-August (Northern) / January-February (Southern)",
  53L,    "Zebra Turkeyfish",              "Sea",        "Medium",    500,                          "All day",                                   "April-November (Northern) / October-May (Southern)",
  54L,            "Blowfish",              "Sea",        "Medium",   5000,                  "6 p.m. - 4 a.m.",                                 "November-February (Northern) / May-August (Southern)",
  55L,         "Puffer Fish",              "Sea",        "Medium",    250,                          "All day",                                 "July-September (Northern) / January-March (Southern)",
  56L,             "Anchovy",              "Sea",         "Small",    200,                  "4 a.m. - 9 p.m.",                                                   "Year-round (Northern and Southern)",
  57L,      "Horse Mackerel",              "Sea",         "Small",    150,                          "All day",                                                   "Year-round (Northern and Southern)",
  58L,     "Barred Knifejaw",              "Sea",        "Medium",   5000,                          "All day",                                 "March-November (Northern) / September-May (Southern)",
  59L,            "Sea Bass",              "Sea",       "X Large",    400,                          "All day",                                                   "Year-round (Northern and Southern)",
  60L,         "Red Snapper",              "Sea",         "Large",   3000,                          "All day",                                                   "Year-round (Northern and Southern)",
  61L,                 "Dab",              "Sea",        "Medium",    300,                          "All day",                                  "October-April (Northern) / April-October (Southern)",
  62L,      "Olive Flounder",              "Sea",         "Large",    800,                          "All day",                                                   "Year-round (Northern and Southern)",
  63L,               "Squid",              "Sea",        "Medium",    500,                          "All day",                                "December-August (Northern) / June-February (Southern)",
  64L,           "Moray Eel",              "Sea",        "Narrow",   2000,                          "All day",                                "August-October (Northern) / February-April (Southern)",
  65L,          "Ribbon Eel",              "Sea",        "Narrow",    600,                          "All day",                                  "June-October (Northern) / December-April (Southern)",
  66L,                "Tuna",             "Pier",       "Largest",   7000,                          "All day",                                   "November-April (Northern) / May-October (Southern)",
  67L,         "Blue Marlin",             "Pier",       "Largest",  10000,                          "All day",   "July-September, November-April (Northern) / January-March, May-November (Southern)",
  68L,      "Giant Trevally",             "Pier",         "Large",   4500,                          "All day",                                   "May-October (Northern) / November-April (Southern)",
  69L,           "Mahi-mahi",             "Pier",         "Large",   6000,                          "All day",                                   "May-October (Northern) / November-April (Southern)",
  70L,       "Ocean Sunfish",              "Sea", "Largest (Fin)",   4000,                  "4 a.m. - 9 p.m.",                                 "July-September (Northern) / January-March (Southern)",
  71L,                 "Ray",              "Sea",       "X Large",   3000,                  "4 a.m. - 9 p.m.",                                 "August-November (Northern) / February-May (Southern)",
  72L,           "Saw Shark",              "Sea", "Largest (Fin)",  12000,                  "4 p.m. - 9 a.m.",                                "June-September (Northern) / December-March (Southern)",
  73L,    "Hammerhead Shark",              "Sea", "Largest (Fin)",   8000,                  "4 p.m. - 9 a.m.",                                "June-September (Northern) / December-March (Southern)",
  74L,   "Great White Shark",              "Sea", "Largest (Fin)",  15000,                  "4 p.m. - 9 a.m.",                                "June-September (Northern) / December-March (Southern)",
  75L,         "Whale Shark",              "Sea", "Largest (Fin)",  13000,                          "All day",                                "June-September (Northern) / December-March (Southern)",
  76L,          "Suckerfish",              "Sea",   "Large (Fin)",   1500,                          "All day",                                "June-September (Northern) / December-March (Southern)",
  77L,       "Football Fish",              "Sea",         "Large",   2500,                  "4 p.m. - 9 a.m.",                                 "November-March (Northern) / May-September (Southern)",
  78L,             "Oarfish",              "Sea",       "Largest",   9000,                          "All day",                                   "December-May (Northern) / June-November (Southern)",
  79L,           "Barreleye",              "Sea",         "Small",  15000,                  "9 p.m. - 4 a.m.",                                                   "Year-round (Northern and Southern)",
  80L,          "Coelacanth", "Sea (rainy days)",       "Largest",  15000,                          "All day",                                                   "Year-round (Northern and Southern)"
)

pdat <- as.data.frame(pdat)

save(pdat,file = 'PolygonData.RData')
